# -*- coding: utf-8 -*-
"""trab_ML-01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Natassiam/40d44781a0b7f1834a30ce6452f1d688/trab_ml-01.ipynb
"""

import pandas as pd
import numpy as np

from sklearn import datasets

df = pd.read_csv('/content/testes_Simple.csv', sep=';')

df.head()

"""df.head"""

df.mean()

df.head

df.columns

df.head().T

df.info()

from sklearn.model_selection import train_test_split

print(df)

import scipy.stats as st

x = np.random.normal(size=1000)
plt.hist(x, density=True, bins=30, label="Data")
mn, mx = plt.xlim()
plt.xlim(mn, mx)
kde_xs = np.linspace(mn, mx, 301)
kde = st.gaussian_kde(x)
plt.plot(kde_xs, kde.pdf(kde_xs), label="PDF")
plt.legend(loc="upper left")
plt.ylabel('Probability')
plt.xlabel('Data')
plt.title("Histogram");

x = np.arange(3)
plt.bar(x, height=[1,2,3])
plt.xticks(x, ['a','b','c'])

df['nom_tipocombustivel2'].hist()

import matplotlib.pyplot as plt

plt.plot('nom_tipocombustivel2')

df.describe()
#definindo parametros para os graficos